import { FlaskConical, Scale, UsersRound } from "lucide-react";
import { getOperationsData } from "../../../src/db/commercial";
import { EmptyState, PageHeader, StatusBadge, formatDateTime } from "../_components";

export default async function ExperimentsPage() {
  const { experiments } = await getOperationsData();
  return <>
    <PageHeader eyebrow="Otimização responsável" title="Experimentos" description="Uma variável principal por vez, com métrica clara e sem declarar vencedor antes da amostra mínima." />
    {!experiments.length?<EmptyState title="Nenhum experimento" description="Crie um teste quando houver hipótese comercial concreta e volume suficiente para aprender."/>:<div className="space-y-4">{experiments.map(exp=>{const progress=Math.min(100,exp.sampleSize/exp.minimumSampleSize*100);return <article className="rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:p-6" key={exp.id}><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><span className="grid size-11 shrink-0 place-items-center rounded-[14px] bg-[#eee2f0] text-[#74527b]"><FlaskConical size={19}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-bold text-[#294653]">{exp.hypothesis}</h2><StatusBadge status={exp.status}/></div><p className="mt-1 text-[10px] text-[#8a959b]">Iniciado {formatDateTime(exp.startedAt)} · Métrica primária: {exp.primaryMetric}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-[16px] bg-[#f7f5ee] p-4"><p className="text-[9px] font-bold uppercase tracking-wide text-[#8b979d]">Controle</p><p className="mt-2 text-xs font-semibold text-[#526873]">{exp.control}</p></div><div className="rounded-[16px] bg-[#fff3ee] p-4"><p className="text-[9px] font-bold uppercase tracking-wide text-[#bd5b42]">Variante</p><p className="mt-2 text-xs font-semibold text-[#526873]">{exp.variant}</p></div></div><div className="mt-5"><div className="mb-2 flex items-center justify-between text-[9px] text-[#7e8b91]"><span className="flex items-center gap-1.5"><UsersRound size={12}/>{exp.sampleSize} de {exp.minimumSampleSize} contatos mínimos</span><strong>{Math.round(progress)}%</strong></div><div className="h-2 overflow-hidden rounded-full bg-[#edeee9]"><span className="block h-full rounded-full bg-[#e8795d]" style={{width:`${progress}%`}}/></div></div>{exp.sampleSize<exp.minimumSampleSize&&<p className="mt-3 flex items-center gap-2 text-[9px] font-semibold text-[#8a671b]"><Scale size={12}/>Amostra insuficiente: nenhum vencedor será declarado.</p>}</div></div></article>})}</div>}
  </>;
}
