import { AlertTriangle, AtSign as Instagram, CheckCircle2, Clock3, MessageCircle, Pause, Settings2, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { getBusinessConfig, isDefinedBusinessValue } from "../../../src/config/business";
import { getOperationsData } from "../../../src/db/commercial";
import { PageHeader } from "../_components";
import { updateAutomationSetting, updateBusinessConfiguration } from "../actions";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ salvo?: string; erro?: string }> }) {
  const [business,ops,params]=await Promise.all([getBusinessConfig(),getOperationsData(),searchParams]);
  const whatsappReady=isDefinedBusinessValue(business.company.whatsappLink);
  const settings=[
    {key:"automation_paused",label:"Automação geral",description:"Interrompe toda a execução automática",icon:Pause},
    {key:"outbound_paused",label:"Outbound",description:"Primeiro contato automático",icon:Instagram},
    {key:"followups_paused",label:"Follow-ups",description:"Retomadas contextuais limitadas",icon:Clock3},
    {key:"auto_replies_paused",label:"Respostas automáticas",description:"Envio de respostas geradas",icon:MessageCircle},
  ];
  return <>
    <PageHeader eyebrow="Governança" title="Configurações" description="Dados obrigatórios, limites e chaves de operação ficam centralizados e auditados." />
    {params.salvo&&<p className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs text-emerald-800">Configuração salva com segurança.</p>}{params.erro&&<p className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-800">{params.erro}</p>}
    <div className="grid gap-5 xl:grid-cols-[1.05fr_.95fr]">
      <section className="rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[13px] bg-[#dce8f6] text-[#425d91]"><Settings2 size={18}/></span><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Negócio</p><h2 className="text-base font-semibold">Dados obrigatórios</h2></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-[15px] bg-[#f7f5ee] p-4"><p className="text-[8px] font-bold uppercase tracking-wide text-[#8b979d]">Empresa</p><p className="mt-1 text-xs font-bold text-[#415967]">{business.company.name}</p></div><div className="rounded-[15px] bg-[#f7f5ee] p-4"><p className="text-[8px] font-bold uppercase tracking-wide text-[#8b979d]">Responsável</p><p className="mt-1 text-xs font-bold text-[#415967]">{business.owner.name}</p></div></div><form action={updateBusinessConfiguration} className="mt-5 space-y-4"><label className="block"><span className="mb-1.5 flex items-center justify-between text-[9px] font-bold uppercase tracking-wide text-[#718088]"><span>Link oficial do WhatsApp</span>{whatsappReady?<span className="flex items-center gap-1 text-[#4f956f]"><CheckCircle2 size={11}/>Configurado</span>:<span className="flex items-center gap-1 text-[#b85841]"><AlertTriangle size={11}/>Obrigatório para handoff</span>}</span><input name="whatsappLink" defaultValue={business.company.whatsappLink} className="h-11 w-full rounded-xl border border-[#dfe2de] bg-[#faf9f6] px-3 text-xs outline-none focus:border-[#e07a5f]"/></label><label className="block"><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-wide text-[#718088]">Região de atendimento/entrega</span><input name="fulfillmentGeography" defaultValue={business.fulfillmentGeography} className="h-11 w-full rounded-xl border border-[#dfe2de] bg-[#faf9f6] px-3 text-xs outline-none focus:border-[#e07a5f]"/></label><button className="rounded-xl bg-[#e56e50] px-5 py-3 text-xs font-bold text-white">Salvar dados do negócio</button></form><p className="mt-4 flex items-start gap-2 text-[9px] leading-4 text-[#8a959b]"><ShieldCheck size={13} className="mt-0.5 shrink-0"/>Valores A_DEFINIR nunca são preenchidos automaticamente. O arquivo real permanece fora do Git.</p></section>
      <section className="rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[13px] bg-[#fff0c9] text-[#8b6718]"><SlidersHorizontal size={18}/></span><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Controles</p><h2 className="text-base font-semibold">Pausas operacionais</h2></div></div><div className="mt-5 divide-y divide-[#ecece7]">{settings.map(item=>{const Icon=item.icon;const paused=ops.settings[item.key]==="true";return <div className="flex items-center gap-3 py-4" key={item.key}><span className={`grid size-9 shrink-0 place-items-center rounded-xl ${paused?"bg-[#fff0c9] text-[#8b6718]":"bg-[#d8ede4] text-[#2b7258]"}`}><Icon size={16}/></span><div className="min-w-0 flex-1"><p className="text-xs font-bold text-[#415967]">{item.label}</p><p className="mt-0.5 text-[9px] text-[#8a959b]">{item.description}</p></div><form action={updateAutomationSetting}><input type="hidden" name="key" value={item.key}/><input type="hidden" name="value" value={paused?"false":"true"}/><button className={`rounded-full px-3 py-1.5 text-[9px] font-bold ${paused?"bg-[#f8ddd7] text-[#9c4031]":"bg-[#d8ede4] text-[#2b7258]"}`}>{paused?"Pausado":"Ativo"}</button></form></div>})}</div></section>
    </div>
    <section className="mt-5 rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Integrações</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-[16px] bg-[#f7f5ee] p-4"><Instagram size={17} className="text-[#5979aa]"/><p className="mt-3 text-xs font-bold">Instagram oficial</p><p className="mt-1 text-[9px] text-[#8a959b]">Webhook preparado · credenciais pendentes</p></div><div className="rounded-[16px] bg-[#f7f5ee] p-4"><MessageCircle size={17} className="text-[#4c9a73]"/><p className="mt-3 text-xs font-bold">WhatsApp</p><p className="mt-1 text-[9px] text-[#8a959b]">{whatsappReady?"Handoff habilitado":"Bloqueado até configurar link"}</p></div><div className="rounded-[16px] bg-[#f7f5ee] p-4"><ShieldCheck size={17} className="text-[#d96245]"/><p className="mt-3 text-xs font-bold">Outbound</p><p className="mt-1 text-[9px] text-[#8a959b]">Desabilitado por padrão e sujeito a autorização</p></div></div></section>
  </>;
}
