import { AlertTriangle, AtSign as Instagram, CheckCircle2, Clock3, MessageCircle, Pause, RefreshCw, Settings2, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { getBusinessConfig, isDefinedBusinessValue } from "../../../src/config/business";
import { getOperationsData } from "../../../src/db/commercial";
import { getInstagramIntegrationState } from "../../../src/integrations/instagram/token-store";
import { PageHeader, formatDateTime } from "../_components";
import { runInstagramReliabilityCheck, updateAutomationSetting, updateBusinessConfiguration } from "../actions";
import { getFollowupSchedulerStatus } from "../../../src/worker/followup-scheduler";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ salvo?: string; erro?: string; verificado?: string }> }) {
  const [business,ops,params,instagramState]=await Promise.all([getBusinessConfig(),getOperationsData(),searchParams,getInstagramIntegrationState()]);
  const whatsappReady=isDefinedBusinessValue(business.company.whatsappLink);
  const followupScheduler=getFollowupSchedulerStatus();
  const instagramReady=Boolean(process.env.INSTAGRAM_PAGE_ACCESS_TOKEN?.trim()&&process.env.INSTAGRAM_APP_SECRET?.trim()&&process.env.INSTAGRAM_BUSINESS_ACCOUNT_ID?.trim());
  const browserConfigured=Boolean(process.env.CHROME_CDP_URL?.trim()&&process.env.CHROME_PROFILE_DIR?.trim());
  const browserSendReady=browserConfigured&&process.env.OUTBOUND_AUTOMATION_ENABLED==="true"&&process.env.BROWSER_SEND_ENABLED==="true";
  const browserState=ops.integrations.find(item=>item.key==="instagram_browser");
  const settings=[
    {key:"automation_paused",label:"Automação geral",description:"Interrompe toda a execução automática",icon:Pause},
    {key:"outbound_paused",label:"Outbound",description:"Prospecção assistida sob política",icon:Instagram},
    {key:"followups_paused",label:"Follow-ups",description:"Retomadas contextuais limitadas",icon:Clock3},
    {key:"auto_replies_paused",label:"Respostas automáticas",description:"Envio de respostas geradas",icon:MessageCircle},
  ];
  return <>
    <PageHeader eyebrow="Governança" title="Configurações" description="Dados obrigatórios, limites e chaves de operação ficam centralizados e auditados." />
    {params.salvo&&<p className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs text-emerald-800">Configuração salva com segurança.</p>}{params.erro&&<p className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-800">{params.erro}</p>}
    {params.verificado&&<p className={`mb-4 rounded-xl border px-4 py-3 text-xs ${params.verificado==="healthy"?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-amber-200 bg-amber-50 text-amber-800"}`}>Verificação concluída. Webhook, token e reconciliação foram atualizados.</p>}
    <div className="grid gap-5 xl:grid-cols-[1.05fr_.95fr]">
      <section className="rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[13px] bg-[#dce8f6] text-[#425d91]"><Settings2 size={18}/></span><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Negócio</p><h2 className="text-base font-semibold">Dados obrigatórios</h2></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-[15px] bg-[#f7f5ee] p-4"><p className="text-[8px] font-bold uppercase tracking-wide text-[#8b979d]">Empresa</p><p className="mt-1 text-xs font-bold text-[#415967]">{business.company.name}</p></div><div className="rounded-[15px] bg-[#f7f5ee] p-4"><p className="text-[8px] font-bold uppercase tracking-wide text-[#8b979d]">Responsável</p><p className="mt-1 text-xs font-bold text-[#415967]">{business.owner.name}</p></div></div><form action={updateBusinessConfiguration} className="mt-5 space-y-4"><label className="block"><span className="mb-1.5 flex items-center justify-between text-[9px] font-bold uppercase tracking-wide text-[#718088]"><span>Link oficial do WhatsApp</span>{whatsappReady?<span className="flex items-center gap-1 text-[#4f956f]"><CheckCircle2 size={11}/>Configurado</span>:<span className="flex items-center gap-1 text-[#b85841]"><AlertTriangle size={11}/>Obrigatório para handoff</span>}</span><input name="whatsappLink" defaultValue={business.company.whatsappLink} className="h-11 w-full rounded-xl border border-[#dfe2de] bg-[#faf9f6] px-3 text-xs outline-none focus:border-[#e07a5f]"/></label><label className="block"><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-wide text-[#718088]">Região de atendimento/entrega</span><input name="fulfillmentGeography" defaultValue={business.fulfillmentGeography} className="h-11 w-full rounded-xl border border-[#dfe2de] bg-[#faf9f6] px-3 text-xs outline-none focus:border-[#e07a5f]"/></label><button className="rounded-xl bg-[#e56e50] px-5 py-3 text-xs font-bold text-white">Salvar dados do negócio</button></form><p className="mt-4 flex items-start gap-2 text-[9px] leading-4 text-[#8a959b]"><ShieldCheck size={13} className="mt-0.5 shrink-0"/>Valores A_DEFINIR nunca são preenchidos automaticamente. O arquivo real permanece fora do Git.</p></section>
      <section className="rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[13px] bg-[#fff0c9] text-[#8b6718]"><SlidersHorizontal size={18}/></span><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Controles</p><h2 className="text-base font-semibold">Pausas operacionais</h2></div></div><div className="mt-5 divide-y divide-[#ecece7]">{settings.map(item=>{const Icon=item.icon;const paused=ops.settings[item.key]==="true";return <div className="flex items-center gap-3 py-4" key={item.key}><span className={`grid size-9 shrink-0 place-items-center rounded-xl ${paused?"bg-[#fff0c9] text-[#8b6718]":"bg-[#d8ede4] text-[#2b7258]"}`}><Icon size={16}/></span><div className="min-w-0 flex-1"><p className="text-xs font-bold text-[#415967]">{item.label}</p><p className="mt-0.5 text-[9px] text-[#8a959b]">{item.description}</p></div><form action={updateAutomationSetting}><input type="hidden" name="key" value={item.key}/><input type="hidden" name="value" value={paused?"false":"true"}/><button className={`rounded-full px-3 py-1.5 text-[9px] font-bold ${paused?"bg-[#f8ddd7] text-[#9c4031]":"bg-[#d8ede4] text-[#2b7258]"}`}>{paused?"Pausado":"Ativo"}</button></form></div>})}</div></section>
    </div>
    <section className="mt-5 rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Integrações</p><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><div className="rounded-[16px] bg-[#f7f5ee] p-4"><Instagram size={17} className="text-[#5979aa]"/><p className="mt-3 text-xs font-bold">Instagram oficial</p><p className="mt-1 text-[9px] text-[#8a959b]">{instagramReady?"Webhook e envio assistido configurados":"Configuração incompleta"}</p></div><div className="rounded-[16px] bg-[#f7f5ee] p-4"><MessageCircle size={17} className="text-[#4c9a73]"/><p className="mt-3 text-xs font-bold">WhatsApp</p><p className="mt-1 text-[9px] text-[#8a959b]">{whatsappReady?"Handoff habilitado":"Bloqueado até configurar link"}</p></div><div className="rounded-[16px] bg-[#f7f5ee] p-4"><Clock3 size={17} className="text-[#8b6718]"/><p className="mt-3 text-xs font-bold">Agendador de follow-up</p><p className="mt-1 text-[9px] text-[#8a959b]">{followupScheduler.ready?"QStash autenticado e pronto":"Aguardando configuração externa do QStash"}</p></div><div className="rounded-[16px] bg-[#f7f5ee] p-4"><Instagram size={17} className="text-[#74527b]"/><p className="mt-3 text-xs font-bold">Chrome dedicado</p><p className="mt-1 text-[9px] text-[#8a959b]">{browserState?.status==="error"?"Circuit breaker aberto":browserSendReady?"Configurado e liberado":browserConfigured?"Configurado, envio bloqueado":"Disponível somente no worker local"}</p></div><div className="rounded-[16px] bg-[#f7f5ee] p-4"><ShieldCheck size={17} className="text-[#d96245]"/><p className="mt-3 text-xs font-bold">Outbound</p><p className="mt-1 text-[9px] text-[#8a959b]">DM fria via API permanece bloqueada</p></div></div></section>
    <section className="mt-5 rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><RefreshCw size={16} className={instagramState?.status==="error"?"text-red-600":"text-[#2f7c60]"}/><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Confiabilidade do Instagram</p></div><h2 className="mt-2 text-base font-semibold">{instagramState?.status==="healthy"?"Integração saudável":instagramState?.status==="warning"?"Integração funcionando com aviso":instagramState?.status==="error"?"Integração requer atenção":"Aguardando primeira verificação"}</h2><p className="mt-1 text-[10px] leading-4 text-[#7c8a90]">Última sincronização: {formatDateTime(instagramState?.lastSuccessfulSyncAt)} · Token: {instagramState?.tokenExpiresAt?`válido até ${formatDateTime(instagramState.tokenExpiresAt)}`:"validade será confirmada na renovação"}</p>{instagramState?.lastError&&<p className="mt-2 max-w-3xl rounded-lg bg-amber-50 px-3 py-2 text-[10px] text-amber-800">{instagramState.lastError}</p>}</div><form action={runInstagramReliabilityCheck}><button className="flex shrink-0 items-center justify-center gap-2 rounded-xl bg-[#193848] px-4 py-3 text-[10px] font-bold text-white"><RefreshCw size={14}/>Verificar agora</button></form></div></section>
  </>;
}
