import { AlertTriangle, CircleDollarSign, Clock3, PackagePlus, Plus } from "lucide-react";
import { getCatalog } from "../../../src/db/commercial";
import { evaluateCatalogTruth } from "../../../src/features/leads/domain";
import { EmptyState, PageHeader, formatBrl } from "../_components";
import { addCatalogProduct } from "../actions";

export default async function ProductsPage({ searchParams }: { searchParams: Promise<{ salvo?: string; erro?: string }> }) {
  const [products,params] = await Promise.all([getCatalog(),searchParams]);
  return <>
    <PageHeader eyebrow="Fonte de verdade" title="Catálogo comercial" description="Preço, prazo e possibilidades só podem ser afirmados quando estiverem cadastrados aqui." />
    {params.salvo&&<p className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs text-emerald-800">Produto cadastrado com sucesso.</p>}{params.erro&&<p className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-800">{params.erro}</p>}
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
      <section>{!products.length?<EmptyState title="Catálogo vazio" description="Cadastre o primeiro produto para a IA ter uma fonte comercial verificável."/>:<div className="grid gap-4 md:grid-cols-2">{products.map(product=>{const truth=evaluateCatalogTruth(product);return <article className="rounded-[22px] border border-[#e1e1db] bg-white p-5 shadow-[0_8px_28px_rgba(32,52,60,.04)]" key={product.id}><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-[#f5f2e9] px-2.5 py-1 text-[8px] font-bold uppercase tracking-wide text-[#806826]">{product.category||"Sem categoria"}</span><h2 className="mt-3 text-base font-semibold tracking-[-0.025em] text-[#294653]">{product.name}</h2></div><span className={`size-2 rounded-full ${product.active?"bg-[#69b894]":"bg-[#a9afad]"}`}/></div><p className="mt-2 line-clamp-2 min-h-10 text-[10px] leading-5 text-[#7d8a90]">{product.description||"Descrição ainda não cadastrada."}</p><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-[#f7f5ee] p-3"><p className="flex items-center gap-1.5 text-[8px] font-bold uppercase tracking-wide text-[#8b979d]"><CircleDollarSign size={11}/>Preço</p><p className="mt-1 text-xs font-bold text-[#415967]">{product.basePriceCents!=null?formatBrl(product.basePriceCents):product.priceFromCents!=null?`A partir de ${formatBrl(product.priceFromCents)}`:"Sob orçamento"}</p></div><div className="rounded-xl bg-[#f7f5ee] p-3"><p className="flex items-center gap-1.5 text-[8px] font-bold uppercase tracking-wide text-[#8b979d]"><Clock3 size={11}/>Produção</p><p className="mt-1 truncate text-xs font-bold text-[#415967]">{product.productionTime||"Revisão necessária"}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{truth.needsQuote&&<span className="flex items-center gap-1 rounded-full bg-[#fff0c9] px-2.5 py-1 text-[8px] font-bold text-[#846214]"><AlertTriangle size={10}/>Não estimar preço</span>}{truth.needsProductionReview&&<span className="flex items-center gap-1 rounded-full bg-[#f8ddd7] px-2.5 py-1 text-[8px] font-bold text-[#9c4031]"><AlertTriangle size={10}/>Não prometer prazo</span>}</div></article>})}</div>}</section>
      <aside className="h-fit rounded-[22px] bg-[#193848] p-6 text-white"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[13px] bg-[#f1c865] text-[#193848]"><PackagePlus size={18}/></span><div><p className="text-[9px] font-bold uppercase tracking-[0.13em] text-white/45">Cadastro seguro</p><h2 className="text-base font-semibold">Novo produto</h2></div></div><form action={addCatalogProduct} className="mt-5 space-y-3">{[{name:"name",label:"Nome",placeholder:"Ex.: Topo de bolo personalizado"},{name:"category",label:"Categoria",placeholder:"Festas"},{name:"basePrice",label:"Preço base (opcional)",placeholder:"89,90"},{name:"productionTime",label:"Prazo de produção (opcional)",placeholder:"Só cadastre se estiver validado"}].map(field=><label className="block" key={field.name}><span className="mb-1.5 block text-[8px] font-bold uppercase tracking-wide text-white/45">{field.label}</span><input name={field.name} required={field.name==="name"} placeholder={field.placeholder} className="h-10 w-full rounded-xl border border-white/10 bg-white/8 px-3 text-xs text-white outline-none placeholder:text-white/25 focus:border-[#f1c865]/60"/></label>)}<label className="block"><span className="mb-1.5 block text-[8px] font-bold uppercase tracking-wide text-white/45">Descrição</span><textarea name="description" rows={3} className="w-full resize-none rounded-xl border border-white/10 bg-white/8 p-3 text-xs text-white outline-none placeholder:text-white/25 focus:border-[#f1c865]/60" placeholder="O que está comercialmente verificado?"/></label><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#f1c865] px-4 py-3 text-xs font-extrabold text-[#193848]"><Plus size={15}/>Cadastrar produto</button></form></aside>
    </div>
  </>;
}
