import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, ArrowLeft, AtSign as Instagram, Bot, CheckCircle2, ClipboardCheck, ExternalLink, MessageCircle, MoveRight, Send, ShieldCheck, UserRoundCheck } from "lucide-react";
import { SubmitButton } from "../../../components/PendingButton";
import { getLeadDetail } from "../../../../src/db/commercial";
import { getBusinessConfig, isDefinedBusinessValue } from "../../../../src/config/business";
import { buildBriefingSummary, CHANNEL_STATE_LABELS, CONSUMER_PIPELINE, INTENT_LABELS, PIPELINE_LABELS, type Intent } from "../../../../src/features/leads/domain";
import { OUTBOUND_PIPELINES, OUTBOUND_PIPELINE_LABELS } from "../../../../src/features/outbound/domain";
import { isConversationMessageVisible } from "../../../../src/features/conversations/presentation";
import { Avatar, StatusBadge, formatBrl, formatDateTime } from "../../_components";
import { approveInstagramReply, blockLeadContact, confirmCommercialOrder, createInstagramReplyDraft, escalateInstagramConversation, registerQuote, registerWhatsappHandoff, updateLeadStage } from "../../actions";

export default async function LeadDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ simulado?: string; rascunho?: string; enviado?: string; escalado?: string; erro?: string }> }) {
  const [{ id }, query] = await Promise.all([params, searchParams]);
  const [detail, business] = await Promise.all([getLeadDetail(id), getBusinessConfig()]);
  if (!detail) notFound();
  const { lead, conversation, messages, briefing, timeline } = detail;
  const pipelineOptions = lead.leadType === "partner" ? OUTBOUND_PIPELINES.partner : CONSUMER_PIPELINE;
  const visibleMessages = messages.filter(isConversationMessageVisible);
  const commentReviewOnly = Boolean(
    conversation?.externalId?.startsWith("comment:"),
  );
  const whatsappReady = isDefinedBusinessValue(business.company.whatsappLink);
  const summary = buildBriefingSummary(lead.instagramUsername, briefing || { productInterest: lead.productInterest, occasion: lead.occasion });
  const scores = [
    ["Intenção", lead.intentScore, 35], ["ICP", lead.icpScore, 20], ["Engajamento", lead.engagementScore, 20], ["Potencial", lead.commercialPotentialScore, 15], ["Urgência", lead.urgencyScore, 10],
  ] as const;
  const pendingReply = [...messages].reverse().find((message) => message.direction === "outbound" && ["draft", "failed", "sending", "send_uncertain"].includes(message.status));
  const latestInbound = [...messages].reverse().find((message) => message.direction === "inbound");
  const latestSent = [...messages].reverse().find((message) => message.direction === "outbound" && message.status === "sent");
  const canPrepareReply = Boolean(conversation && !pendingReply && latestInbound && (!latestSent || Date.parse(latestInbound.sentAt) > Date.parse(latestSent.sentAt)));
  return <>
    <Link href="/comercial/leads" className="mb-5 inline-flex items-center gap-2 text-xs font-bold text-[#6f7e86] hover:text-[#d96245]"><ArrowLeft size={14}/>Voltar aos leads</Link>
    {query.simulado && <div className="mb-5 flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs text-emerald-800"><CheckCircle2 size={16}/>Inbound processado: classificação, score, briefing e job foram persistidos.</div>}
    {query.rascunho && <div className="mb-5 flex items-center gap-3 rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-xs text-blue-800"><Bot size={16}/>Rascunho preparado. Revise o texto antes de enviar.</div>}
    {query.enviado && <div className="mb-5 flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs text-emerald-800"><CheckCircle2 size={16}/>Resposta enviada pelo Instagram e registrada na auditoria.</div>}
    {query.escalado && <div className="mb-5 flex items-center gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-800"><UserRoundCheck size={16}/>Conversa encaminhada para atendimento humano.</div>}
    {query.erro && <div className="mb-5 flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-800"><AlertTriangle size={16}/>{query.erro}</div>}
    <header className="mb-6 flex flex-col gap-5 rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:flex-row sm:items-center sm:p-6">
      <Avatar name={lead.name} username={lead.instagramUsername} size="lg"/>
      <div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-[-0.04em] text-[#173244]">{lead.name || `@${lead.instagramUsername}`}</h1><StatusBadge status={lead.pipelineStage}/></div><p className="mt-1 flex items-center gap-1.5 text-xs text-[#7b898f]"><Instagram size={13}/>@{lead.instagramUsername} · {lead.source}</p></div>
      <div className="flex items-center gap-3"><div className="text-right"><p className="text-[9px] font-bold uppercase tracking-[0.12em] text-[#8e999e]">Lead score</p><p className="text-3xl font-semibold tracking-[-0.05em] text-[#e06649]">{lead.score}</p></div><div className="h-11 w-px bg-[#e6e6e1]"/><form action={updateLeadStage} className="flex items-center gap-2"><input type="hidden" name="leadId" value={lead.id}/><select name="pipelineStage" defaultValue={lead.pipelineStage} className="h-10 rounded-xl border border-[#dfe2de] bg-[#faf9f6] px-3 text-[10px] font-bold text-[#526873] outline-none">{pipelineOptions.map(stage=><option key={stage} value={stage}>{PIPELINE_LABELS[stage as keyof typeof PIPELINE_LABELS] || OUTBOUND_PIPELINE_LABELS[stage]}</option>)}</select><SubmitButton pendingLabel="Movendo…" className="flex h-10 items-center justify-center gap-1.5 rounded-xl bg-[#173244] px-3 text-[9px] font-bold text-white disabled:opacity-60">Mover</SubmitButton></form></div>
    </header>
    <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <div className="space-y-5">
        <section className="overflow-hidden rounded-[22px] border border-[#e1e1db] bg-white">
          <header className="flex items-center justify-between border-b border-[#ecece7] px-5 py-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Histórico completo</p><h2 className="mt-1 text-base font-semibold">Conversa no Instagram</h2></div><span className="text-[9px] font-bold text-[#7c8a90]">{visibleMessages.length} mensagens</span></header>
          <div className="max-h-[620px] space-y-4 overflow-y-auto bg-[#f8f7f3] p-5">{visibleMessages.map((message)=>{
            const editable=message.direction==="outbound"&&["draft","failed"].includes(message.status);
            const uncertain=message.status==="send_uncertain";
            if(editable&&commentReviewOnly)return <div className="ml-auto max-w-[92%] rounded-2xl rounded-br-md border border-amber-200 bg-amber-50 p-4 shadow-sm" key={message.id}><div className="mb-2 flex items-center gap-1.5 text-[9px] font-bold uppercase tracking-wide text-amber-800"><UserRoundCheck size={12}/>Rascunho para revisão humana</div><p className="whitespace-pre-wrap text-xs leading-5 text-[#344f5c]">{message.body}</p><p className="mt-3 text-[9px] leading-4 text-amber-800">Comentário capturado para análise. Este rascunho não pode ser enviado como DM.</p></div>;
            if(editable)return <form action={approveInstagramReply} className="ml-auto max-w-[92%] rounded-2xl rounded-br-md border border-[#c9d9df] bg-white p-4 shadow-sm" key={message.id}><input type="hidden" name="leadId" value={lead.id}/><input type="hidden" name="messageId" value={message.id}/><div className="mb-2 flex items-center justify-between gap-3"><span className="flex items-center gap-1.5 text-[9px] font-bold uppercase tracking-wide text-[#4f7180]"><Bot size={12}/>Rascunho para revisão</span>{message.status==="failed"&&<span className="text-[9px] font-bold text-red-600">Último envio recusado</span>}</div><textarea name="body" required maxLength={1000} defaultValue={message.body} aria-label="Texto da resposta" rows={5} className="w-full resize-y rounded-xl border border-[#dfe5e7] bg-[#fafcfc] p-3 text-xs leading-5 text-[#344f5c] outline-none focus:border-[#4f7b8d]"/><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><span className="text-[9px] text-[#8a959b]">Edite livremente antes da aprovação.</span><SubmitButton pendingLabel="Enviando…" className="flex items-center gap-2 rounded-xl bg-[#2f7c60] px-4 py-2.5 text-[10px] font-bold text-white disabled:opacity-60"><Send size={13}/>Aprovar e enviar</SubmitButton></div></form>;
            return <div className={`flex ${message.direction==="outbound"?"justify-end":"justify-start"}`} key={message.id}><div className={`max-w-[82%] rounded-2xl px-4 py-3 text-xs leading-5 shadow-sm ${message.direction==="outbound"?"rounded-br-md bg-[#193848] text-white":"rounded-bl-md border border-[#e3e2dc] bg-white text-[#435966]"}`}><p>{message.body}</p><div className={`mt-2 flex items-center justify-between gap-4 text-[8px] ${message.direction==="outbound"?"text-white/50":"text-[#9aa3a7]"}`}><span>{uncertain?"Envio incerto — confira no Instagram":message.status==="sending"?"Enviando…":message.intent ? INTENT_LABELS[message.intent as Intent] || "Intenção não classificada" : "Sem classificação"}</span><span>{formatDateTime(message.sentAt)}</span></div></div></div>;
          })}{!visibleMessages.length&&<p className="py-8 text-center text-xs text-[#8d989c]">A conversa ainda não possui mensagens.</p>}</div>
          {conversation && <footer className="flex items-center gap-3 border-t border-[#ecece7] px-5 py-3 text-[10px] text-[#809097]"><ShieldCheck size={14} className="text-[#5aa483]"/>Canal: Instagram · {CHANNEL_STATE_LABELS[lead.channelState] || "Estado não identificado"} · Responsável técnico: {conversation.channelOwner === "api" ? "API oficial" : conversation.channelOwner === "browser" ? "navegador dedicado" : "revisão humana"}</footer>}
        </section>
        {canPrepareReply&&<section className="rounded-[22px] border border-[#d9e3e7] bg-white p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold text-[#344f5c]">Preparar resposta assistida</p><p className="mt-1 text-[10px] text-[#7c8a90]">A sugestão ficará como rascunho e não será enviada automaticamente.</p></div><form action={createInstagramReplyDraft}><input type="hidden" name="leadId" value={lead.id}/><SubmitButton pendingLabel="Gerando…" className="flex items-center gap-2 rounded-xl bg-[#193848] px-4 py-3 text-[10px] font-bold text-white disabled:opacity-60"><Bot size={14}/>Gerar rascunho</SubmitButton></form></div></section>}
        <section className="rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[13px] bg-[#f8ded5] text-[#a24d36]"><Bot size={18}/></span><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Decisão estruturada</p><h2 className="text-base font-semibold">Próxima melhor ação</h2></div></div><div className="mt-5 rounded-[16px] bg-[#f7f5ee] p-4"><p className="text-xs font-bold text-[#344f5c]">Validar viabilidade e responder ao pedido de orçamento</p><p className="mt-1 text-[11px] leading-5 text-[#78868c]">O sistema não confirma preço, prazo ou possibilidade técnica sem uma fonte cadastrada. A conversa está pronta para revisão humana.</p></div></section>
      </div>
      <aside className="space-y-5">
        {!lead.doNotContact&&<form action={blockLeadContact} className="rounded-[22px] border border-[#efc9bd] bg-[#fff5f1] p-5"><input type="hidden" name="leadId" value={lead.id}/><p className="text-xs font-bold text-[#8e4435]">Lista permanente de não contato</p><p className="mt-1 text-[10px] leading-4 text-[#8e6a62]">Bloqueia mensagens e cancela jobs abertos deste lead em todas as campanhas.</p><SubmitButton pendingLabel="Bloqueando…" className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#a94f3c] px-4 py-2.5 text-[10px] font-bold text-white disabled:opacity-60">Bloquear novos contatos</SubmitButton></form>}
        <form action={escalateInstagramConversation} className="rounded-[22px] border border-[#e1e1db] bg-white p-5"><input type="hidden" name="leadId" value={lead.id}/><div className="flex items-start gap-3"><UserRoundCheck className="mt-0.5 text-[#806147]" size={18}/><div className="flex-1"><p className="text-xs font-bold text-[#344f5c]">Atendimento humano</p><p className="mt-1 text-[10px] leading-4 text-[#7c8a90]">Sinalize a conversa nas exceções sem enviar nenhuma mensagem.</p></div></div><SubmitButton pendingLabel="Encaminhando…" className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-[#d9d6cf] bg-[#faf9f6] px-4 py-2.5 text-[10px] font-bold text-[#526873] disabled:opacity-60">Encaminhar para humano</SubmitButton></form>
        <section className="rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Qualificação</p><h2 className="mt-1 text-base font-semibold">Composição do score</h2></div><span className="text-3xl font-semibold text-[#e06649]">{lead.score}</span></div><div className="mt-5 space-y-3">{scores.map(([label,value,max])=><div key={label}><div className="mb-1.5 flex justify-between text-[9px] font-semibold text-[#718088]"><span>{label}</span><span>{value}/{max}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#edeee9]"><span className="block h-full rounded-full bg-[#e4795c]" style={{width:`${Math.min(100,value/max*100)}%`}}/></div></div>)}</div></section>
        <section className="rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><ClipboardCheck className="text-[#d96245]" size={18}/><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Briefing automático</p><h2 className="text-base font-semibold">Resumo para o fechamento</h2></div></div><pre className="mt-4 whitespace-pre-wrap rounded-[16px] bg-[#f7f5ee] p-4 font-sans text-[11px] leading-5 text-[#526873]">{summary}</pre></section>
        <section className={`rounded-[22px] p-5 ${whatsappReady?"bg-[#dcefe7]":"border border-[#efc9bd] bg-[#fff5f1]"}`}>
          <div className="flex items-start gap-3">{whatsappReady?<MessageCircle className="mt-0.5 text-[#2f7c60]" size={19}/>:<AlertTriangle className="mt-0.5 text-[#bd5b42]" size={19}/>}<div><p className="text-xs font-bold text-[#344f5c]">{whatsappReady?"Handoff disponível":"Handoff bloqueado com segurança"}</p><p className="mt-1 text-[10px] leading-4 text-[#74838a]">{whatsappReady?"O resumo está pronto para o atendimento humano.":"WHATSAPP_LINK continua A_DEFINIR. Nenhum link fictício será enviado."}</p></div></div>{whatsappReady?<form action={registerWhatsappHandoff} className="mt-4"><input type="hidden" name="leadId" value={lead.id}/><SubmitButton pendingLabel="Registrando…" className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#2f7c60] px-4 py-3 text-xs font-bold text-white disabled:opacity-60">Registrar e abrir WhatsApp <ExternalLink size={14}/></SubmitButton></form>:<Link href="/comercial/configuracoes" className="mt-4 flex items-center justify-center gap-2 rounded-xl bg-[#193848] px-4 py-3 text-xs font-bold text-white">Completar configuração <MoveRight size={14}/></Link>}</section>
        {lead.quoteStatus!=="sent"&&lead.quoteStatus!=="accepted"?<form action={registerQuote} className="rounded-[22px] border border-[#e1e1db] bg-white p-5"><input type="hidden" name="leadId" value={lead.id}/><label className="block text-[9px] font-bold uppercase tracking-[0.12em] text-[#8b979d]">Registrar orçamento aprovado pelo operador</label><div className="mt-3 flex gap-2"><input name="amount" required inputMode="decimal" placeholder="Valor em R$" className="h-10 min-w-0 flex-1 rounded-xl border border-[#dfe2de] bg-[#faf9f6] px-3 text-xs outline-none"/><SubmitButton pendingLabel="Salvando…" className="flex items-center justify-center gap-1.5 rounded-xl bg-[#e56e50] px-4 text-[10px] font-bold text-white disabled:opacity-60">Salvar</SubmitButton></div></form>:<section className="rounded-[22px] border border-[#e1e1db] bg-white p-5"><p className="text-[9px] font-bold uppercase tracking-[0.12em] text-[#8b979d]">Orçamento atual</p><p className="mt-2 text-2xl font-semibold text-[#173244]">{formatBrl(lead.estimatedOrderValueCents||lead.confirmedOrderValueCents)}</p>{lead.orderStatus!=="confirmed"&&<form action={confirmCommercialOrder} className="mt-4"><input type="hidden" name="leadId" value={lead.id}/><SubmitButton pendingLabel="Confirmando…" className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#193848] px-4 py-3 text-xs font-bold text-white disabled:opacity-60"><CheckCircle2 size={15}/>Confirmar pedido</SubmitButton></form>}</section>}
        <section className="rounded-[22px] border border-[#e1e1db] bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Linha do tempo</p><div className="mt-4 space-y-4">{timeline.map((event)=><div className="flex gap-3" key={event.id}><span className="mt-1.5 size-2 shrink-0 rounded-full bg-[#e8795d] shadow-[0_0_0_4px_rgba(232,121,93,.1)]"/><div><p className="text-[11px] font-bold text-[#415967]">{event.title}</p><p className="mt-0.5 text-[9px] text-[#929ca0]">{formatDateTime(event.createdAt)} · {event.createdBy}</p></div></div>)}</div></section>
      </aside>
    </div>
  </>;
}
