import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, ArrowLeft, AtSign as Instagram, Bot, CheckCircle2, ClipboardCheck, ExternalLink, MessageCircle, MoveRight, ShieldCheck } from "lucide-react";
import { getLeadDetail } from "../../../../src/db/commercial";
import { getBusinessConfig, isDefinedBusinessValue } from "../../../../src/config/business";
import { buildBriefingSummary, CHANNEL_STATE_LABELS, CONSUMER_PIPELINE, INTENT_LABELS, PIPELINE_LABELS, type Intent } from "../../../../src/features/leads/domain";
import { Avatar, StatusBadge, formatBrl, formatDateTime } from "../../_components";
import { confirmCommercialOrder, registerQuote, registerWhatsappHandoff, updateLeadStage } from "../../actions";

export default async function LeadDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ simulado?: string }> }) {
  const [{ id }, query] = await Promise.all([params, searchParams]);
  const [detail, business] = await Promise.all([getLeadDetail(id), getBusinessConfig()]);
  if (!detail) notFound();
  const { lead, conversation, messages, briefing, timeline } = detail;
  const whatsappReady = isDefinedBusinessValue(business.company.whatsappLink);
  const summary = buildBriefingSummary(lead.instagramUsername, briefing || { productInterest: lead.productInterest, occasion: lead.occasion });
  const scores = [
    ["Intenção", lead.intentScore, 35], ["ICP", lead.icpScore, 20], ["Engajamento", lead.engagementScore, 20], ["Potencial", lead.commercialPotentialScore, 15], ["Urgência", lead.urgencyScore, 10],
  ] as const;
  return <>
    <Link href="/comercial/leads" className="mb-5 inline-flex items-center gap-2 text-xs font-bold text-[#6f7e86] hover:text-[#d96245]"><ArrowLeft size={14}/>Voltar aos leads</Link>
    {query.simulado && <div className="mb-5 flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs text-emerald-800"><CheckCircle2 size={16}/>Inbound processado: classificação, score, briefing e job foram persistidos.</div>}
    <header className="mb-6 flex flex-col gap-5 rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:flex-row sm:items-center sm:p-6">
      <Avatar name={lead.name} username={lead.instagramUsername} size="lg"/>
      <div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-[-0.04em] text-[#173244]">{lead.name || `@${lead.instagramUsername}`}</h1><StatusBadge status={lead.pipelineStage}/></div><p className="mt-1 flex items-center gap-1.5 text-xs text-[#7b898f]"><Instagram size={13}/>@{lead.instagramUsername} · {lead.source}</p></div>
      <div className="flex items-center gap-3"><div className="text-right"><p className="text-[9px] font-bold uppercase tracking-[0.12em] text-[#8e999e]">Lead score</p><p className="text-3xl font-semibold tracking-[-0.05em] text-[#e06649]">{lead.score}</p></div><div className="h-11 w-px bg-[#e6e6e1]"/><form action={updateLeadStage} className="flex items-center gap-2"><input type="hidden" name="leadId" value={lead.id}/><select name="pipelineStage" defaultValue={lead.pipelineStage} className="h-10 rounded-xl border border-[#dfe2de] bg-[#faf9f6] px-3 text-[10px] font-bold text-[#526873] outline-none">{CONSUMER_PIPELINE.map(stage=><option key={stage} value={stage}>{PIPELINE_LABELS[stage]}</option>)}</select><button className="h-10 rounded-xl bg-[#173244] px-3 text-[9px] font-bold text-white">Mover</button></form></div>
    </header>
    <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <div className="space-y-5">
        <section className="overflow-hidden rounded-[22px] border border-[#e1e1db] bg-white">
          <header className="flex items-center justify-between border-b border-[#ecece7] px-5 py-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Histórico completo</p><h2 className="mt-1 text-base font-semibold">Conversa no Instagram</h2></div><span className="text-[9px] font-bold text-[#7c8a90]">{messages.length} mensagens</span></header>
          <div className="max-h-[520px] space-y-4 overflow-y-auto bg-[#f8f7f3] p-5">{messages.map((message)=><div className={`flex ${message.direction==="outbound"?"justify-end":"justify-start"}`} key={message.id}><div className={`max-w-[82%] rounded-2xl px-4 py-3 text-xs leading-5 shadow-sm ${message.direction==="outbound"?"rounded-br-md bg-[#193848] text-white":"rounded-bl-md border border-[#e3e2dc] bg-white text-[#435966]"}`}><p>{message.body}</p><div className={`mt-2 flex items-center justify-between gap-4 text-[8px] ${message.direction==="outbound"?"text-white/40":"text-[#9aa3a7]"}`}><span>{message.intent ? INTENT_LABELS[message.intent as Intent] || "Intenção não classificada" : "Sem classificação"}</span><span>{formatDateTime(message.sentAt)}</span></div></div></div>)}{!messages.length&&<p className="py-8 text-center text-xs text-[#8d989c]">A conversa ainda não possui mensagens.</p>}</div>
          {conversation && <footer className="flex items-center gap-3 border-t border-[#ecece7] px-5 py-3 text-[10px] text-[#809097]"><ShieldCheck size={14} className="text-[#5aa483]"/>Canal: Instagram · {CHANNEL_STATE_LABELS[lead.channelState] || "Estado não identificado"}</footer>}
        </section>
        <section className="rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[13px] bg-[#f8ded5] text-[#a24d36]"><Bot size={18}/></span><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Decisão estruturada</p><h2 className="text-base font-semibold">Próxima melhor ação</h2></div></div><div className="mt-5 rounded-[16px] bg-[#f7f5ee] p-4"><p className="text-xs font-bold text-[#344f5c]">Validar viabilidade e responder ao pedido de orçamento</p><p className="mt-1 text-[11px] leading-5 text-[#78868c]">O sistema não confirma preço, prazo ou possibilidade técnica sem uma fonte cadastrada. A conversa está pronta para revisão humana.</p></div></section>
      </div>
      <aside className="space-y-5">
        <section className="rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Qualificação</p><h2 className="mt-1 text-base font-semibold">Composição do score</h2></div><span className="text-3xl font-semibold text-[#e06649]">{lead.score}</span></div><div className="mt-5 space-y-3">{scores.map(([label,value,max])=><div key={label}><div className="mb-1.5 flex justify-between text-[9px] font-semibold text-[#718088]"><span>{label}</span><span>{value}/{max}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#edeee9]"><span className="block h-full rounded-full bg-[#e4795c]" style={{width:`${Math.min(100,value/max*100)}%`}}/></div></div>)}</div></section>
        <section className="rounded-[22px] border border-[#e1e1db] bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><ClipboardCheck className="text-[#d96245]" size={18}/><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Briefing automático</p><h2 className="text-base font-semibold">Resumo para o fechamento</h2></div></div><pre className="mt-4 whitespace-pre-wrap rounded-[16px] bg-[#f7f5ee] p-4 font-sans text-[11px] leading-5 text-[#526873]">{summary}</pre></section>
        <section className={`rounded-[22px] p-5 ${whatsappReady?"bg-[#dcefe7]":"border border-[#efc9bd] bg-[#fff5f1]"}`}>
          <div className="flex items-start gap-3">{whatsappReady?<MessageCircle className="mt-0.5 text-[#2f7c60]" size={19}/>:<AlertTriangle className="mt-0.5 text-[#bd5b42]" size={19}/>}<div><p className="text-xs font-bold text-[#344f5c]">{whatsappReady?"Handoff disponível":"Handoff bloqueado com segurança"}</p><p className="mt-1 text-[10px] leading-4 text-[#74838a]">{whatsappReady?"O resumo está pronto para o atendimento humano.":"WHATSAPP_LINK continua A_DEFINIR. Nenhum link fictício será enviado."}</p></div></div>{whatsappReady?<form action={registerWhatsappHandoff} className="mt-4"><input type="hidden" name="leadId" value={lead.id}/><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#2f7c60] px-4 py-3 text-xs font-bold text-white">Registrar e abrir WhatsApp <ExternalLink size={14}/></button></form>:<Link href="/comercial/configuracoes" className="mt-4 flex items-center justify-center gap-2 rounded-xl bg-[#193848] px-4 py-3 text-xs font-bold text-white">Completar configuração <MoveRight size={14}/></Link>}</section>
        {lead.quoteStatus!=="sent"&&lead.quoteStatus!=="accepted"?<form action={registerQuote} className="rounded-[22px] border border-[#e1e1db] bg-white p-5"><input type="hidden" name="leadId" value={lead.id}/><label className="block text-[9px] font-bold uppercase tracking-[0.12em] text-[#8b979d]">Registrar orçamento aprovado pelo operador</label><div className="mt-3 flex gap-2"><input name="amount" required inputMode="decimal" placeholder="Valor em R$" className="h-10 min-w-0 flex-1 rounded-xl border border-[#dfe2de] bg-[#faf9f6] px-3 text-xs outline-none"/><button className="rounded-xl bg-[#e56e50] px-4 text-[10px] font-bold text-white">Salvar</button></div></form>:<section className="rounded-[22px] border border-[#e1e1db] bg-white p-5"><p className="text-[9px] font-bold uppercase tracking-[0.12em] text-[#8b979d]">Orçamento atual</p><p className="mt-2 text-2xl font-semibold text-[#173244]">{formatBrl(lead.estimatedOrderValueCents||lead.confirmedOrderValueCents)}</p>{lead.orderStatus!=="confirmed"&&<form action={confirmCommercialOrder} className="mt-4"><input type="hidden" name="leadId" value={lead.id}/><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#193848] px-4 py-3 text-xs font-bold text-white"><CheckCircle2 size={15}/>Confirmar pedido</button></form>}</section>}
        <section className="rounded-[22px] border border-[#e1e1db] bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Linha do tempo</p><div className="mt-4 space-y-4">{timeline.map((event)=><div className="flex gap-3" key={event.id}><span className="mt-1.5 size-2 shrink-0 rounded-full bg-[#e8795d] shadow-[0_0_0_4px_rgba(232,121,93,.1)]"/><div><p className="text-[11px] font-bold text-[#415967]">{event.title}</p><p className="mt-0.5 text-[9px] text-[#929ca0]">{formatDateTime(event.createdAt)} · {event.createdBy}</p></div></div>)}</div></section>
      </aside>
    </div>
  </>;
}
