import { AtSign as Instagram, PauseCircle, Radio, ShieldOff, Target } from "lucide-react";
import { getOperationsData } from "../../../src/db/commercial";
import { EmptyState, PageHeader, StatusBadge, formatDateTime } from "../_components";
import { createCampaign } from "../actions";

export default async function CampaignsPage({ searchParams }: { searchParams: Promise<{ salvo?: string; erro?: string }> }) {
  const [{ campaigns }, params] = await Promise.all([getOperationsData(), searchParams]);
  return <>
    <PageHeader eyebrow="Origem e estratégia" title="Campanhas" description="Acompanhe a origem das oportunidades sem otimizar para volume de mensagens." action={<span className="inline-flex items-center gap-2 rounded-full bg-[#fff0c9] px-3 py-2 text-[9px] font-bold text-[#846214]"><ShieldOff size={13}/>Outbound desativado</span>}/>
    {params.salvo&&<p className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs text-emerald-800">Campanha criada com outbound bloqueado.</p>}{params.erro&&<p className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-800">{params.erro}</p>}
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section>{!campaigns.length?<EmptyState title="Nenhuma campanha" description="Crie uma campanha para organizar origem e segmento das oportunidades."/>:<div className="grid gap-4 lg:grid-cols-2">{campaigns.map((campaign,index)=><article className="rounded-[22px] border border-[#e1e1db] bg-white p-5" key={campaign.id}><div className="flex items-start justify-between"><span className={`grid size-10 place-items-center rounded-[13px] ${index%2?"bg-[#fff0c9] text-[#8b6718]":"bg-[#dce8f6] text-[#425d91]"}`}>{campaign.source==="Instagram"?<Instagram size={18}/>:<Target size={18}/>}</span><StatusBadge status={campaign.status}/></div><h2 className="mt-5 text-base font-semibold text-[#294653]">{campaign.name}</h2><p className="mt-1 text-[10px] text-[#859197]">{campaign.source} · {campaign.segment||"Sem segmento"}</p><div className="mt-5 flex items-center justify-between border-t border-[#eeeae3] pt-4"><span className="flex items-center gap-1.5 text-[9px] text-[#8a959b]">{campaign.status==="active"?<Radio size={11}/>:<PauseCircle size={11}/>}Atualizado {formatDateTime(campaign.updatedAt)}</span><span className={`text-[9px] font-bold ${campaign.outboundEnabled?"text-[#b74a31]":"text-[#5c9a7c]"}`}>Outbound {campaign.outboundEnabled?"ativo":"bloqueado"}</span></div></article>)}</div>}</section><aside className="h-fit rounded-[22px] bg-[#193848] p-6 text-white"><h2 className="text-base font-semibold">Nova campanha</h2><p className="mt-2 text-[10px] leading-4 text-white/55">O cadastro organiza atribuição. Nenhum primeiro contato será habilitado.</p><form action={createCampaign} className="mt-5 space-y-3">{[{name:"name",label:"Nome",placeholder:"Inbound orgânico"},{name:"source",label:"Origem",placeholder:"Instagram"},{name:"segment",label:"Segmento",placeholder:"Presentes personalizados"}].map(field=><label className="block" key={field.name}><span className="mb-1.5 block text-[8px] font-bold uppercase tracking-wide text-white/45">{field.label}</span><input name={field.name} required={field.name!=="segment"} placeholder={field.placeholder} className="h-10 w-full rounded-xl border border-white/10 bg-white/8 px-3 text-xs text-white outline-none placeholder:text-white/25"/></label>)}<button className="w-full rounded-xl bg-[#f1c865] px-4 py-3 text-xs font-extrabold text-[#193848]">Criar campanha segura</button></form></aside></div>
  </>;
}
