import Link from "next/link";
import { AtSign as Instagram, Bot, ExternalLink, PauseCircle, Radio, ShieldCheck, ShieldOff, Target, UserPlus } from "lucide-react";
import { getOperationsData, getOutboundProspects } from "../../../src/db/commercial";
import { EmptyState, PageHeader, StatusBadge, formatDateTime } from "../_components";
import { addOutboundProspect, createCampaign, prepareOutboundProspectDraft, saveOutboundProspectDraft, setOutboundCampaignEnabled } from "../actions";

type SearchParams = { salvo?: string; erro?: string; prospecto?: string; rascunho?: string; revisado?: string; campanha?: string };

const policyLabels: Record<string, string> = {
  inbound_window: "DM inbound dentro de 24h",
  manual_only: "Primeiro contato somente manual",
  comment_private_reply: "Resposta privada a comentário",
};

export default async function CampaignsPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const [{ campaigns, settings }, prospects, params] = await Promise.all([getOperationsData(), getOutboundProspects(), searchParams]);
  const globallyReady = process.env.OUTBOUND_AUTOMATION_ENABLED === "true" && settings.automation_paused !== "true" && settings.outbound_paused === "false";

  return <>
    <PageHeader eyebrow="Origem e estratégia" title="Campanhas e prospecção" description="Qualifique oportunidades, prepare abordagens e preserve as regras de contato de cada canal." action={<span className={`inline-flex items-center gap-2 rounded-full px-3 py-2 text-[9px] font-bold ${globallyReady ? "bg-[#d8ede4] text-[#2b7258]" : "bg-[#fff0c9] text-[#846214]"}`}>{globallyReady ? <ShieldCheck size={13}/> : <ShieldOff size={13}/>} {globallyReady ? "Liberação global ativa" : "Envio outbound bloqueado"}</span>}/>
    {(params.salvo || params.prospecto || params.rascunho || params.revisado || params.campanha) && <p className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs text-emerald-800">Alteração salva. Nenhuma mensagem externa foi enviada.</p>}
    {params.erro && <p className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-800">{params.erro}</p>}

    <section className="mb-5 rounded-[22px] border border-[#e5d6aa] bg-[#fff9e8] p-5"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-[#8b6718]" size={18}/><div><h2 className="text-sm font-bold text-[#54461f]">Prospecção assistida, com envio separado</h2><p className="mt-1 max-w-4xl text-[10px] leading-5 text-[#756735]">A API oficial do Instagram só envia mensagens em contextos permitidos. Perfis sem conversa inbound válida ficam como contato manual; preparar ou aprovar um texto aqui nunca dispara uma DM.</p></div></div></section>

    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
      <section>{!campaigns.length ? <EmptyState title="Nenhuma campanha" description="Crie uma campanha para organizar origem e segmento das oportunidades."/> : <div className="grid gap-4 lg:grid-cols-2">{campaigns.map((campaign,index)=><article className="rounded-[22px] border border-[#e1e1db] bg-white p-5" key={campaign.id}><div className="flex items-start justify-between"><span className={`grid size-10 place-items-center rounded-[13px] ${index%2 ? "bg-[#fff0c9] text-[#8b6718]" : "bg-[#dce8f6] text-[#425d91]"}`}>{campaign.source === "Instagram" ? <Instagram size={18}/> : <Target size={18}/>}</span><StatusBadge status={campaign.status}/></div><h2 className="mt-5 text-base font-semibold text-[#294653]">{campaign.name}</h2><p className="mt-1 text-[10px] text-[#859197]">{campaign.source} · {campaign.segment || "Sem segmento"}</p><div className="mt-5 flex items-center justify-between border-t border-[#eeeae3] pt-4"><span className="flex items-center gap-1.5 text-[9px] text-[#8a959b]">{campaign.status === "active" ? <Radio size={11}/> : <PauseCircle size={11}/>}Atualizado {formatDateTime(campaign.updatedAt)}</span><form action={setOutboundCampaignEnabled}><input type="hidden" name="campaignId" value={campaign.id}/><input type="hidden" name="enabled" value={campaign.outboundEnabled ? "false" : "true"}/><button className={`rounded-full px-3 py-1.5 text-[9px] font-bold ${campaign.outboundEnabled ? "bg-[#f8ddd7] text-[#9c4031]" : "bg-[#edf0ed] text-[#65746c]"}`}>{campaign.outboundEnabled ? "Pausar outbound" : "Solicitar ativação"}</button></form></div></article>)}</div>}</section>
      <aside className="h-fit rounded-[22px] bg-[#193848] p-6 text-white"><h2 className="text-base font-semibold">Nova campanha</h2><p className="mt-2 text-[10px] leading-4 text-white/55">O cadastro nasce como rascunho e sem autorização de envio.</p><form action={createCampaign} className="mt-5 space-y-3">{[{name:"name",label:"Nome",placeholder:"Parcerias locais"},{name:"source",label:"Origem",placeholder:"Instagram"},{name:"segment",label:"Segmento",placeholder:"Arquitetura e decoração"}].map(field=><label className="block" key={field.name}><span className="mb-1.5 block text-[8px] font-bold uppercase tracking-wide text-white/45">{field.label}</span><input name={field.name} required={field.name !== "segment"} placeholder={field.placeholder} className="h-10 w-full rounded-xl border border-white/10 bg-white/8 px-3 text-xs text-white outline-none placeholder:text-white/25"/></label>)}<button className="w-full rounded-xl bg-[#f1c865] px-4 py-3 text-xs font-extrabold text-[#193848]">Criar campanha segura</button></form></aside>
    </div>

    <div className="mt-5 grid gap-5 xl:grid-cols-[.7fr_1.3fr]">
      <section className="h-fit rounded-[22px] border border-[#e1e1db] bg-white p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[13px] bg-[#dce8f6] text-[#425d91]"><UserPlus size={18}/></span><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Qualificação</p><h2 className="text-base font-semibold">Adicionar prospecto</h2></div></div>{campaigns.length ? <form action={addOutboundProspect} className="mt-5 space-y-3"><select name="campaignId" required className="h-11 w-full rounded-xl border border-[#dfe2de] bg-[#faf9f6] px-3 text-xs outline-none"><option value="">Selecione uma campanha</option>{campaigns.map(campaign=><option key={campaign.id} value={campaign.id}>{campaign.name}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><input name="instagramUsername" required placeholder="@perfil" className="h-11 rounded-xl border border-[#dfe2de] bg-[#faf9f6] px-3 text-xs outline-none"/><input name="name" placeholder="Nome (opcional)" className="h-11 rounded-xl border border-[#dfe2de] bg-[#faf9f6] px-3 text-xs outline-none"/></div><input name="sourceUrl" type="url" placeholder="https://www.instagram.com/perfil" className="h-11 w-full rounded-xl border border-[#dfe2de] bg-[#faf9f6] px-3 text-xs outline-none"/><textarea name="qualificationReason" required minLength={10} maxLength={500} rows={4} placeholder="Por que este perfil é relevante para a campanha?" className="w-full resize-y rounded-xl border border-[#dfe2de] bg-[#faf9f6] p-3 text-xs leading-5 outline-none"/><button className="w-full rounded-xl bg-[#193848] px-4 py-3 text-xs font-bold text-white">Adicionar sem contatar</button></form> : <p className="mt-5 text-xs text-[#7c8a90]">Crie uma campanha antes de adicionar prospectos.</p>}</section>

      <section className="overflow-hidden rounded-[22px] border border-[#e1e1db] bg-white"><header className="border-b border-[#ecece7] px-5 py-4"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#8b979d]">Fila de prospecção</p><h2 className="mt-1 text-base font-semibold">{prospects.length} prospectos qualificados</h2></header>{!prospects.length ? <div className="p-5"><EmptyState title="Fila vazia" description="Perfis adicionados aparecerão aqui sem receber contato automático."/></div> : <div className="divide-y divide-[#ecece7]">{prospects.map(({prospect,campaign,lead})=><article className="p-5" key={prospect.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-[#294653]">{prospect.name || `@${prospect.instagramUsername}`}</p><p className="mt-1 text-[10px] text-[#859197]">@{prospect.instagramUsername} · {campaign.name}</p></div><span className={`rounded-full px-3 py-1.5 text-[9px] font-bold ${prospect.contactPolicy === "inbound_window" ? "bg-[#d8ede4] text-[#2b7258]" : "bg-[#fff0c9] text-[#846214]"}`}>{policyLabels[prospect.contactPolicy] || prospect.contactPolicy}</span></div><p className="mt-3 text-[10px] leading-5 text-[#657780]">{prospect.qualificationReason}</p>{prospect.draftBody ? <form action={saveOutboundProspectDraft} className="mt-4 rounded-xl bg-[#f7f5ee] p-3"><input type="hidden" name="prospectId" value={prospect.id}/><textarea name="draftBody" defaultValue={prospect.draftBody} maxLength={1000} rows={4} className="w-full resize-y rounded-lg border border-[#dfe2de] bg-white p-3 text-[11px] leading-5 outline-none"/><div className="mt-2 flex flex-wrap items-center justify-between gap-2"><span className="text-[9px] text-[#8a959b]">Aprovação registra o texto; não envia.</span><button className="rounded-lg bg-[#2f7c60] px-3 py-2 text-[9px] font-bold text-white">Salvar revisão</button></div></form> : <form action={prepareOutboundProspectDraft} className="mt-4"><input type="hidden" name="prospectId" value={prospect.id}/><button className="inline-flex items-center gap-2 rounded-xl bg-[#193848] px-4 py-2.5 text-[10px] font-bold text-white"><Bot size={13}/>Preparar rascunho</button></form>}<div className="mt-3 flex flex-wrap gap-3 text-[9px] font-bold">{prospect.sourceUrl && <Link href={prospect.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-[#587795]">Ver fonte <ExternalLink size={10}/></Link>}{lead && <Link href={`/comercial/leads/${lead.id}`} className="text-[#2f7c60]">Abrir lead relacionado</Link>}</div></article>)}</div>}</section>
    </div>
  </>;
}
