import { AtSign as Instagram, PackageCheck, ShoppingBag, TrendingUp } from "lucide-react";
import { getOrdersOverview } from "../../../src/db/commercial";
import { Avatar, EmptyState, LeadLink, PageHeader, StatusBadge, formatBrl, formatDateTime } from "../_components";

export default async function CommercialOrdersPage() {
  const rows = await getOrdersOverview();
  const revenue = rows.reduce((sum,row)=>sum+row.order.amountCents,0);
  return <>
    <PageHeader eyebrow="Conversão" title="Pedidos comerciais" description="Pedidos atribuídos à origem, à conversa e ao briefing que contribuíram para a conversão." action={<a href="/admin/pedidos" className="rounded-xl border border-[#dcded9] bg-white px-4 py-3 text-xs font-bold text-[#526873]">Ver pedidos da loja</a>}/>
    <div className="mb-5 grid gap-4 sm:grid-cols-3"><div className="rounded-[20px] bg-[#193848] p-5 text-white"><ShoppingBag size={19} className="text-[#f1c865]"/><p className="mt-4 text-[10px] font-bold uppercase tracking-wide text-white/45">Pedidos confirmados</p><p className="mt-1 text-3xl font-semibold">{rows.length}</p></div><div className="rounded-[20px] border border-[#e1e1db] bg-white p-5"><TrendingUp size={19} className="text-[#d96245]"/><p className="mt-4 text-[10px] font-bold uppercase tracking-wide text-[#8b979d]">Receita atribuída</p><p className="mt-1 text-2xl font-semibold">{formatBrl(revenue)}</p></div><div className="rounded-[20px] border border-[#e1e1db] bg-white p-5"><Instagram size={19} className="text-[#5979aa]"/><p className="mt-4 text-[10px] font-bold uppercase tracking-wide text-[#8b979d]">Principal origem</p><p className="mt-1 text-base font-semibold">Instagram inbound</p></div></div>
    {!rows.length?<EmptyState title="Nenhum pedido confirmado" description="Confirme um pedido a partir do lead para registrar a conversão e alimentar o aprendizado comercial."/>:<div className="grid gap-4 lg:grid-cols-2">{rows.map(({order,lead},index)=><article className="rounded-[22px] border border-[#e1e1db] bg-white p-5" key={order.id}><div className="flex items-start gap-3"><Avatar name={lead.name} username={lead.instagramUsername} index={index}/><div className="min-w-0 flex-1"><p className="text-xs font-bold text-[#294653]">{lead.name}</p><p className="mt-0.5 text-[10px] text-[#8a959b]">{order.productCategory||lead.productInterest}</p></div><StatusBadge status={order.status}/></div><div className="mt-5 flex items-end justify-between rounded-[16px] bg-[#f7f5ee] p-4"><div><p className="text-[9px] font-bold uppercase tracking-wide text-[#8b979d]">Valor confirmado</p><p className="mt-1 text-xl font-semibold text-[#173244]">{formatBrl(order.amountCents)}</p></div><PackageCheck className="text-[#5c9a7c]" size={24}/></div><div className="mt-4 flex items-center justify-between"><span className="text-[9px] text-[#8a959b]">{order.source} · {formatDateTime(order.confirmedAt)}</span><LeadLink id={lead.id}>Ver origem</LeadLink></div></article>)}</div>}
  </>;
}
